### PR TITLE
Updated info and schedule for Bilbao

### PR DESCRIPTION
**Pull request by erramuzpe**
Some minor changes. 

I was trying to make our calendar to show, but I couldn't make it. I don't know really if it is the calendar API or any other thing... 
Anyway, our Calendar ID: 4d5komlf0gje9bjdc4eu9if68k .

### CODE REVIEW

**Comment by erramuzpe** [comment]
I will update it later, we could have changes in the registration site.

**Comment by erramuzpe** [comment]
The Calendar seems to work fine now :)

**Comment by erramuzpe** [comment]
Our institution won't handle registrations, so we are using Eventbrite as recommended. :+1:

**Comment by awalensky** [comment]
Thanks for the update!

**Pull request merged**
